<?php

/**
 * Implements hook_theme().
 */
function adminic_toolbar_theme($existing, $type, $theme, $path) {
  $items = [];

  $items['toolbar_top'] = [
    'variables' => [
      'info' => NULL,
    ],
  ];

  $items['toolbar_primary'] = [
    'variables' => [
      'header' => NULL,
      'widgets' => NULL,
      'user_account' => NULL,
    ],
  ];

  $items['toolbar_secondary'] = [
    'variables' => [
      'wrappers' => NULL,
    ],
  ];

  $items['toolbar_header'] = [
    'variables' => [
      'title' => NULL,
      'title_link' => NULL,
      'close' => FALSE,
    ],
  ];

  $items['toolbar_secondary_wrapper'] = [
    'variables' => [
      'header' => NULL,
      'sections' => NULL,
      'active' => FALSE,
      'id' => FALSE,
    ],
  ];

  $items['toolbar_section'] = [
    'variables' => [
      'title' => NULL,
      'links' => NULL,
    ],
  ];

  $items['toolbar_section_tab'] = [
    'variables' => [
      'title' => NULL,
      'route' => NULL,
      'active' => FALSE,
      'id' => NULL,
    ],
  ];

  $items['toolbar_section_link'] = [
    'variables' => [
      'title' => NULL,
      'route' => NULL,
      'active' => FALSE,
    ],
  ];

  $items['user_account'] = [
    'variables' => [
      'avatar' => NULL,
      'dropdown' => NULL,
    ],
  ];

  $items['drd'] = [
    'variables' => [
      'trigger_content' => NULL,
      'content' => NULL,
    ],
  ];

  return $items;
}

/**
 * Implements hook_page_top().
 *
 * Add adminic toolbar to the top of the page automatically.
 *
 * {@inheritdoc}
 */
function adminic_toolbar_page_top(array &$page_top) {
  /** @var \Drupal\adminic_toolbar\Toolbar $adminic_toolbar */
  $adminic_toolbar = \Drupal::service('adminic_toolbar');

  $toolbarPrimary = $adminic_toolbar->getPrimaryToolbar();
  $page_top['adminic_toolbar_primary'] = $toolbarPrimary;

  $toolbarSecondary = $adminic_toolbar->getSecondaryToolbar();
  $page_top['adminic_toolbar_secondary'] = $toolbarSecondary;

  $toolbarTop = $adminic_toolbar->getTopToolbar();
  $page_top['adminic_toolbar_top'] = $toolbarTop;
}

function adminic_toolbar_preprocess_html(&$variables) {
  // Remove default toolbar.
  // TODO: Remove libraries for toolbar.
  if (isset($variables['page_top']['toolbar'])) {
    unset($variables['page_top']['toolbar']);
  }
  if (isset($variables['page_top']['adminic_toolbar_primary'])) {
    $variables['attributes']['class'][] = 'adminic-toolbar-primary';
  }
  if (isset($variables['page_top']['adminic_toolbar_secondary'])) {
    //$variables['attributes']['class'][] = 'adminic-toolbar-secondary';
  }
  if (isset($variables['page_top']['adminic_toolbar_top'])) {
    $variables['attributes']['class'][] = 'adminic-toolbar-top';
  }
}
